version: "3.8"

services:
  nginx:
    build: requirements/nginx/
    image: nginx # after build directive, therefore thats the name of the builded image, an other image.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80" # TODO: remove port 80 (only possible if in vm)
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    env_file: ".env"

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    env_file: ".env"

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file: ".env"
    healthcheck:
      test: ["CMD", "mysqladmin", ping, "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  web:
    name: web
    driver_opts:
      type: none
      o: bind
      device: ${WEB_VOLUME_PATH}
  database:
    name: database
    driver_opts:
      type: none
      o: bind
      device: ${DATABASE_VOLUME_PATH}