version: "3.8"

services:
  nginx:
    build: srcs/requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80" # TODO: remove port 80 (only possible if in vm)
      - "443:443"
    volumes: # TODO: specify path for volumes like specified in subject
      - ./web:/var/www/html
    networks:
      - inception
    restart: always
    env_file: "../.env"

  wordpress:
    build: srcs/requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    restart: always
    env_file: "../.env"

  mariadb:
    build: srcs/requirements/mariadb/
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file: "../.env"
    healthcheck:
      test: ["CMD", "mysqladmin", ping, "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  inception:
    name: inception
    driver: bridge